### ISSUE TITLE
Can't get multiple redmines to SSO

### ISSUE THREAD

**Issue by tramt** [ifad/redmine-cas-plugin#1]
Hello, I have a question related to this pluguin. I’m trying to create a SSO environment using various redmines and other systems. But I’m having an issue, I expect something different to what’s happening. You may can help me on this by giving me a clue about it. (I’m not sure if this is the right place to ask this)

I installed it in the following environment:
PC1: CAS Server, 
PC2: redmine + redmine-cas-plugin, 
PC3: redmine + redmine-cas-plugin.
I configured the pluguins to use my CAS server which is workingin in both redmines. I navitgate to http://pc2/my/page   I get redirected to the CAS (which is right), then I type my credentials, I get redirected and everything is alright. Then I navigate to redmine on PC3 (http://pc3/my/page), I expect to be already authenticated, but I’m not, and I get redirected to the CAS too! Is there anything else I should setup in the pluguin? Can you advice me if this environment is not supported by using this pluguin? Should I make any special modificacion in the pluguin or in the CAS (a rough description will be good)
Thanks for your time.

**Comment by mirek** [comment]
Your scenario should work without redirecting to cas after successful authentication. We've tested your case with 2x fresh Redmine installations on 2 separate Mac computers. You can try the following:
- first of all make sure your browser doesn't block cookies, the whole single sign-on relies on cookies
- also make sure you're using the same browser when opening pages on PC2 and PC3
- I've committed few small changes to the plugin, you may want to update to the most recent version and retry
- do you have any other auth-related plugins installed?

**Comment by tramt** [comment]
Mr. Mirek,

Thanks for your answer. About your points:
1-  My browser (IE & Firefox, Tested on both, with cookies enabled) accept cookies
2-  Same browser used while testing.
3-  I updated your recent pluguin.
4-  No
Anyway, I appreciate your answer, thank you very much. 
I will continue working arround this.

Thank you.

**Comment by mirek** [comment]
...interesting, you may also want to try:
- make sure administration -> settings -> authentication -> authentication required is checked
- make sure on both redmine installations PC2 and PC3 there is user with login name same as your cas username
- if, as a first step you go directly to cas to login - what happens when you open PC2 and PC3 redmines?
- make sure you've got the current version of httpclient gem (2.1.5.2), some older versions have https bugs which can lead to the behaviour described
