### ISSUE TITLE
[Could not login CAS]Missing template account/login_with_cas.erb in view path

### ISSUE THREAD

**Issue by xiebopublic** [ifad/redmine-cas-plugin#8]
My environment: Ubuntu 10.04 TLS 64bit, redmine 1.2.1, the latest redmine-cas-plugin 0.03
## My redmine_cas plugin setting:

Enabled: Checked
CAS base url: https://sso.domain.com/cas
Keep native login link: Checked
Auto create users: Checked
## Update user attributes: Checked

I could login using http://redmine.domain.com/redmine/login for normal (non-cas) login.
But I failed to login http://redmine.domain.com/redmine/account/login_with_cas for CAS login. Below is the Remine error log
------ /var/log/redmine/default/production.log
Processing AccountController#login_with_cas (for 116.237.61.201 at 2012-01-07 11:55:10) [GET]
  Parameters: {"action"=>"login_with_cas", "controller"=>"account"}
Failed login for '' from 116.237.61.201 at Sat Jan 07 03:55:10 UTC 2012

ActionView::MissingTemplate (Missing template account/login_with_cas.erb in view path vendor/plugins/redmine_cas/app/views:app/views):
  app/controllers/application_controller.rb:509:in `default_template'
  /usr/lib/ruby/1.8/phusion_passenger/rack/request_handler.rb:95:in`process_request'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_request_handler.rb:207:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:374:in`start_request_handler'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:332:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/utils.rb:184:in`safe_fork'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:330:in `handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in`**send**'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in`start_synchronously'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:163:in `start'
  /usr/lib/ruby/1.8/phusion_passenger/railz/application_spawner.rb:209:in`start'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:262:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:126:in`lookup_or_add'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:256:in `spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:80:in`synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:255:in`spawn_rails_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:154:in `spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/spawn_manager.rb:287:in`handle_spawn_application'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in `__send__'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:352:in`main_loop'
  /usr/lib/ruby/1.8/phusion_passenger/abstract_server.rb:196:in `start_synchronously'
  /usr/lib/phusion_passenger/passenger-spawn-server:61

**Comment by xiebopublic** [comment]
It is solved after reboot the machine.

**Comment by vjt** [comment]
Thanks for the update.
